package com.vortexbird.seguridad.modelo;
// Generated 14/11/2012 05:54:52 PM by Zathura powered by Hibernate Tools 3.2.4.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * SegAuditoria generated by Zathura powered by Hibernate-tools(hbm2java)
 */
@Entity
@Table(name="SEG_AUDITORIA"
    ,schema="PUBLIC"
)
public class SegAuditoria  implements java.io.Serializable {


     private Long autCodigo;
     private SegUsuario segUsuario;
     private String tabla;
     private Long codRegistro;
     private String campo;
     private String tipo;
     private Date fecha;
     private String valorAnterior;
     private String valorNuevo;

    public SegAuditoria() {
    }

	
    public SegAuditoria(Long autCodigo) {
        this.autCodigo = autCodigo;
    }
    public SegAuditoria(Long autCodigo, SegUsuario segUsuario, String tabla, Long codRegistro, String campo, String tipo, Date fecha, String valorAnterior, String valorNuevo) {
       this.autCodigo = autCodigo;
       this.segUsuario = segUsuario;
       this.tabla = tabla;
       this.codRegistro = codRegistro;
       this.campo = campo;
       this.tipo = tipo;
       this.fecha = fecha;
       this.valorAnterior = valorAnterior;
       this.valorNuevo = valorNuevo;
    }
   
    
    @Id 
  	@SequenceGenerator(name = "seg_auditoria_aut_codigo_seq", sequenceName = "seg_auditoria_aut_codigo_seq")
  	@GeneratedValue(generator = "seg_auditoria_aut_codigo_seq", strategy = GenerationType.SEQUENCE)
    @Column(name="AUT_CODIGO", unique=true, nullable=false)
    public Long getAutCodigo() {
        return this.autCodigo;
    }
    
    public void setAutCodigo(Long autCodigo) {
        this.autCodigo = autCodigo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USU_CODIGO")
    public SegUsuario getSegUsuario() {
        return this.segUsuario;
    }
    
    public void setSegUsuario(SegUsuario segUsuario) {
        this.segUsuario = segUsuario;
    }

    
    @Column(name="TABLA", length=200)
    public String getTabla() {
        return this.tabla;
    }
    
    public void setTabla(String tabla) {
        this.tabla = tabla;
    }

    
    @Column(name="COD_REGISTRO", precision=22, scale=0)
    public Long getCodRegistro() {
        return this.codRegistro;
    }
    
    public void setCodRegistro(Long codRegistro) {
        this.codRegistro = codRegistro;
    }

    
    @Column(name="CAMPO", length=200)
    public String getCampo() {
        return this.campo;
    }
    
    public void setCampo(String campo) {
        this.campo = campo;
    }

    
    @Column(name="TIPO", length=100)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="FECHA", length=7)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="VALOR_ANTERIOR", length=200)
    public String getValorAnterior() {
        return this.valorAnterior;
    }
    
    public void setValorAnterior(String valorAnterior) {
        this.valorAnterior = valorAnterior;
    }

    
    @Column(name="VALOR_NUEVO", length=200)
    public String getValorNuevo() {
        return this.valorNuevo;
    }
    
    public void setValorNuevo(String valorNuevo) {
        this.valorNuevo = valorNuevo;
    }




}


