package co.edu.usbcali.mathusb.modelo;
// Generated 23-mar-2016 0:44:34 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * Asignatura generated by hbm2java
 */
public class Asignatura  implements java.io.Serializable {


     private Long asigId;
     private String nombreAsignatura;
     private Set<Grupo> grupos = new HashSet<Grupo>(0);

    public Asignatura() {
    }

	
    public Asignatura(Long asigId, String nombreAsignatura) {
        this.asigId = asigId;
        this.nombreAsignatura = nombreAsignatura;
    }
    public Asignatura(Long asigId, String nombreAsignatura, Set<Grupo> grupos) {
       this.asigId = asigId;
       this.nombreAsignatura = nombreAsignatura;
       this.grupos = grupos;
    }
   
    public Long getAsigId() {
        return this.asigId;
    }
    
    public void setAsigId(Long asigId) {
        this.asigId = asigId;
    }
    public String getNombreAsignatura() {
        return this.nombreAsignatura;
    }
    
    public void setNombreAsignatura(String nombreAsignatura) {
        this.nombreAsignatura = nombreAsignatura;
    }
    public Set<Grupo> getGrupos() {
        return this.grupos;
    }
    
    public void setGrupos(Set<Grupo> grupos) {
        this.grupos = grupos;
    }




}


