package com.vortexbird.seguridad.modelo;
// Generated 14/11/2012 05:54:52 PM by Zathura powered by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * SegCambioPass generated by Zathura powered by Hibernate-tools(hbm2java)
 */
@Entity
@Table(name="SEG_CAMBIO_PASS"
,schema="PUBLIC"
		)
public class SegCambioPass  implements java.io.Serializable {


	private Long capCodigo;
	private SegUsuario segUsuario;
	private Date capFechaFin;
	private String capToken;
	private String capEstado;
	private Date capFechaIni;

	public SegCambioPass() {
	}


	public SegCambioPass(Long capCodigo) {
		this.capCodigo = capCodigo;
	}
	public SegCambioPass(Long capCodigo, SegUsuario segUsuario, Date capFechaFin, String capToken, String capEstado, Date capFechaIni) {
		this.capCodigo = capCodigo;
		this.segUsuario = segUsuario;
		this.capFechaFin = capFechaFin;
		this.capToken = capToken;
		this.capEstado = capEstado;
		this.capFechaIni = capFechaIni;
	}

	@Id 
	@SequenceGenerator(name = "seg_cambio_pass_cap_codigo_seq", sequenceName = "seg_cambio_pass_cap_codigo_seq")
 	@GeneratedValue(generator = "seg_cambio_pass_cap_codigo_seq", strategy = GenerationType.SEQUENCE)
	@Column(name="CAP_CODIGO", unique=true, nullable=false)
	public Long getCapCodigo() {
		return this.capCodigo;
	}

	public void setCapCodigo(Long capCodigo) {
		this.capCodigo = capCodigo;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="SEG_USUARIO_USU_CODIGO")
	public SegUsuario getSegUsuario() {
		return this.segUsuario;
	}

	public void setSegUsuario(SegUsuario segUsuario) {
		this.segUsuario = segUsuario;
	}


	@Column(name="CAP_FECHA_FIN", length=11)
	public Date getCapFechaFin() {
		return this.capFechaFin;
	}

	public void setCapFechaFin(Date capFechaFin) {
		this.capFechaFin = capFechaFin;
	}


	@Column(name="CAP_TOKEN", length=200)
	public String getCapToken() {
		return this.capToken;
	}

	public void setCapToken(String capToken) {
		this.capToken = capToken;
	}


	@Column(name="CAP_ESTADO", length=50)
	public String getCapEstado() {
		return this.capEstado;
	}

	public void setCapEstado(String capEstado) {
		this.capEstado = capEstado;
	}


	@Column(name="CAP_FECHA_INI", length=11)
	public Date getCapFechaIni() {
		return this.capFechaIni;
	}

	public void setCapFechaIni(Date capFechaIni) {
		this.capFechaIni = capFechaIni;
	}




}


