package com.vortexbird.seguridad.modelo;
// Generated 14/11/2012 05:54:52 PM by Zathura powered by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * SegPermiso generated by Zathura powered by Hibernate-tools(hbm2java)
 */
@Entity
@Table(name="SEG_PERMISO"
,schema="PUBLIC"
		)
public class SegPermiso  implements java.io.Serializable {


	private Long perCodigo;
	private SegUsuario segUsuarioByUsuCodigo;
	private SegRol segRol;
	private SegUsuario segUsuarioByModUsuCodigo;
	private SegOpcion segOpcion;
	private SegSistemaCia segSistemaCia;
	private SegSucursal segSucursal;
	private SegGrupoOpcion segGrupoOpcion;
	private String perEstadoRegistro;

	public SegPermiso() {
	}


	public SegPermiso(Long perCodigo, String perEstadoRegistro) {
		this.perCodigo = perCodigo;
		this.perEstadoRegistro = perEstadoRegistro;
	}
	public SegPermiso(Long perCodigo, SegUsuario segUsuarioByUsuCodigo, SegRol segRol, SegUsuario segUsuarioByModUsuCodigo, SegOpcion segOpcion, SegSistemaCia segSistemaCia, SegSucursal segSucursal, SegGrupoOpcion segGrupoOpcion, String perEstadoRegistro) {
		this.perCodigo = perCodigo;
		this.segUsuarioByUsuCodigo = segUsuarioByUsuCodigo;
		this.segRol = segRol;
		this.segUsuarioByModUsuCodigo = segUsuarioByModUsuCodigo;
		this.segOpcion = segOpcion;
		this.segSistemaCia = segSistemaCia;
		this.segSucursal = segSucursal;
		this.segGrupoOpcion = segGrupoOpcion;
		this.perEstadoRegistro = perEstadoRegistro;
	}

	@Id 
	@SequenceGenerator(name = "seg_permiso_per_codigo_seq", sequenceName = "seg_permiso_per_codigo_seq")
	@GeneratedValue(generator = "seg_permiso_per_codigo_seq", strategy = GenerationType.SEQUENCE)
	@Column(name="PER_CODIGO", unique=true, nullable=false)
	public Long getPerCodigo() {
		return this.perCodigo;
	}

	public void setPerCodigo(Long perCodigo) {
		this.perCodigo = perCodigo;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="USU_CODIGO")
	public SegUsuario getSegUsuarioByUsuCodigo() {
		return this.segUsuarioByUsuCodigo;
	}

	public void setSegUsuarioByUsuCodigo(SegUsuario segUsuarioByUsuCodigo) {
		this.segUsuarioByUsuCodigo = segUsuarioByUsuCodigo;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="ROL_CODIGO")
	public SegRol getSegRol() {
		return this.segRol;
	}

	public void setSegRol(SegRol segRol) {
		this.segRol = segRol;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="MOD_USU_CODIGO")
	public SegUsuario getSegUsuarioByModUsuCodigo() {
		return this.segUsuarioByModUsuCodigo;
	}

	public void setSegUsuarioByModUsuCodigo(SegUsuario segUsuarioByModUsuCodigo) {
		this.segUsuarioByModUsuCodigo = segUsuarioByModUsuCodigo;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="OPC_CODIGO")
	public SegOpcion getSegOpcion() {
		return this.segOpcion;
	}

	public void setSegOpcion(SegOpcion segOpcion) {
		this.segOpcion = segOpcion;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="SIC_CODIGO")
	public SegSistemaCia getSegSistemaCia() {
		return this.segSistemaCia;
	}

	public void setSegSistemaCia(SegSistemaCia segSistemaCia) {
		this.segSistemaCia = segSistemaCia;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="SUC_CODIGO")
	public SegSucursal getSegSucursal() {
		return this.segSucursal;
	}

	public void setSegSucursal(SegSucursal segSucursal) {
		this.segSucursal = segSucursal;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="GRU_CODIGO")
	public SegGrupoOpcion getSegGrupoOpcion() {
		return this.segGrupoOpcion;
	}

	public void setSegGrupoOpcion(SegGrupoOpcion segGrupoOpcion) {
		this.segGrupoOpcion = segGrupoOpcion;
	}


	@Column(name="PER_ESTADO_REGISTRO", nullable=false, length=1)
	public String getPerEstadoRegistro() {
		return this.perEstadoRegistro;
	}

	public void setPerEstadoRegistro(String perEstadoRegistro) {
		this.perEstadoRegistro = perEstadoRegistro;
	}




}


