package com.vortexbird.seguridad.modelo;
// Generated 14/11/2012 05:54:52 PM by Zathura powered by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * SegSistema generated by Zathura powered by Hibernate-tools(hbm2java)
 */
@Entity
@Table(name="SEG_SISTEMA"
,schema="PUBLIC"
		)
public class SegSistema  implements java.io.Serializable {


	private Long sisCodigo;
	private SegUsuario segUsuario;
	private String sisNombre;
	private String sisDescripcion;
	private String sisEstadoRegistro;
	private Set<SegGrupoOpcion> segGrupoOpcions = new HashSet<SegGrupoOpcion>(0);
	private Set<SegSistemaCia> segSistemaCias = new HashSet<SegSistemaCia>(0);
	private Set<SegRol> segRols = new HashSet<SegRol>(0);

	public SegSistema() {
	}


	public SegSistema(Long sisCodigo, String sisNombre, String sisEstadoRegistro) {
		this.sisCodigo = sisCodigo;
		this.sisNombre = sisNombre;
		this.sisEstadoRegistro = sisEstadoRegistro;
	}
	public SegSistema(Long sisCodigo, SegUsuario segUsuario, String sisNombre, String sisDescripcion, String sisEstadoRegistro, Set<SegGrupoOpcion> segGrupoOpcions, Set<SegSistemaCia> segSistemaCias, Set<SegRol> segRols) {
		this.sisCodigo = sisCodigo;
		this.segUsuario = segUsuario;
		this.sisNombre = sisNombre;
		this.sisDescripcion = sisDescripcion;
		this.sisEstadoRegistro = sisEstadoRegistro;
		this.segGrupoOpcions = segGrupoOpcions;
		this.segSistemaCias = segSistemaCias;
		this.segRols = segRols;
	}

	@Id 
	@SequenceGenerator(name = "seg_sistema_sis_codigo_seq", sequenceName = "seg_sistema_sis_codigo_seq")
	@GeneratedValue(generator = "seg_sistema_sis_codigo_seq", strategy = GenerationType.SEQUENCE)
	@Column(name="SIS_CODIGO", unique=true, nullable=false)
	public Long getSisCodigo() {
		return this.sisCodigo;
	}

	public void setSisCodigo(Long sisCodigo) {
		this.sisCodigo = sisCodigo;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="MOD_USU_CODIGO")
	public SegUsuario getSegUsuario() {
		return this.segUsuario;
	}

	public void setSegUsuario(SegUsuario segUsuario) {
		this.segUsuario = segUsuario;
	}


	@Column(name="SIS_NOMBRE", nullable=false, length=50)
	public String getSisNombre() {
		return this.sisNombre;
	}

	public void setSisNombre(String sisNombre) {
		this.sisNombre = sisNombre;
	}


	@Column(name="SIS_DESCRIPCION", length=200)
	public String getSisDescripcion() {
		return this.sisDescripcion;
	}

	public void setSisDescripcion(String sisDescripcion) {
		this.sisDescripcion = sisDescripcion;
	}


	@Column(name="SIS_ESTADO_REGISTRO", nullable=false, length=1)
	public String getSisEstadoRegistro() {
		return this.sisEstadoRegistro;
	}

	public void setSisEstadoRegistro(String sisEstadoRegistro) {
		this.sisEstadoRegistro = sisEstadoRegistro;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="segSistema")
	public Set<SegGrupoOpcion> getSegGrupoOpcions() {
		return this.segGrupoOpcions;
	}

	public void setSegGrupoOpcions(Set<SegGrupoOpcion> segGrupoOpcions) {
		this.segGrupoOpcions = segGrupoOpcions;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="segSistema")
	public Set<SegSistemaCia> getSegSistemaCias() {
		return this.segSistemaCias;
	}

	public void setSegSistemaCias(Set<SegSistemaCia> segSistemaCias) {
		this.segSistemaCias = segSistemaCias;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="segSistema")
	public Set<SegRol> getSegRols() {
		return this.segRols;
	}

	public void setSegRols(Set<SegRol> segRols) {
		this.segRols = segRols;
	}




}


