package co.edu.usbcali.mathusb.modelo;
// Generated 23-mar-2016 0:44:34 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private Long grupId;
     private Asignatura asignatura;
     private String descripcionGrupo;
     private Set<GrupoUsuario> grupoUsuarios = new HashSet<GrupoUsuario>(0);

    public Grupo() {
    }

	
    public Grupo(Long grupId, String descripcionGrupo) {
        this.grupId = grupId;
        this.descripcionGrupo = descripcionGrupo;
    }
    public Grupo(Long grupId, Asignatura asignatura, String descripcionGrupo, Set<GrupoUsuario> grupoUsuarios) {
       this.grupId = grupId;
       this.asignatura = asignatura;
       this.descripcionGrupo = descripcionGrupo;
       this.grupoUsuarios = grupoUsuarios;
    }
   
    public Long getGrupId() {
        return this.grupId;
    }
    
    public void setGrupId(Long grupId) {
        this.grupId = grupId;
    }
    public Asignatura getAsignatura() {
        return this.asignatura;
    }
    
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }
    public String getDescripcionGrupo() {
        return this.descripcionGrupo;
    }
    
    public void setDescripcionGrupo(String descripcionGrupo) {
        this.descripcionGrupo = descripcionGrupo;
    }
    public Set<GrupoUsuario> getGrupoUsuarios() {
        return this.grupoUsuarios;
    }
    
    public void setGrupoUsuarios(Set<GrupoUsuario> grupoUsuarios) {
        this.grupoUsuarios = grupoUsuarios;
    }




}


