package com.vortexbird.seguridad.modelo;
// Generated 14/11/2012 05:54:52 PM by Zathura powered by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SegHistorialConstrasena generated by Zathura powered by Hibernate-tools(hbm2java)
 */
@Entity
@Table(name="SEG_HISTORIAL_CONSTRASENA"
    ,schema="PUBLIC"
)
public class SegHistorialConstrasena  implements java.io.Serializable {


     private Long hcoCodigo;
     private SegUsuario segUsuario;
     private String hcoConstrasena;
     private Date hcoFechaCambio;
     private String hcoDetalleCambio;

    public SegHistorialConstrasena() {
    }

	
    public SegHistorialConstrasena(Long hcoCodigo, SegUsuario segUsuario, String hcoConstrasena, Date hcoFechaCambio) {
        this.hcoCodigo = hcoCodigo;
        this.segUsuario = segUsuario;
        this.hcoConstrasena = hcoConstrasena;
        this.hcoFechaCambio = hcoFechaCambio;
    }
    public SegHistorialConstrasena(Long hcoCodigo, SegUsuario segUsuario, String hcoConstrasena, Date hcoFechaCambio, String hcoDetalleCambio) {
       this.hcoCodigo = hcoCodigo;
       this.segUsuario = segUsuario;
       this.hcoConstrasena = hcoConstrasena;
       this.hcoFechaCambio = hcoFechaCambio;
       this.hcoDetalleCambio = hcoDetalleCambio;
    }
   
     @Id 
    @Column(name="HCO_CODIGO", unique=true, nullable=false, precision=5, scale=0)
    public Long getHcoCodigo() {
        return this.hcoCodigo;
    }
    
    public void setHcoCodigo(Long hcoCodigo) {
        this.hcoCodigo = hcoCodigo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USU_CODIGO", nullable=false)
    public SegUsuario getSegUsuario() {
        return this.segUsuario;
    }
    
    public void setSegUsuario(SegUsuario segUsuario) {
        this.segUsuario = segUsuario;
    }

    
    @Column(name="HCO_CONSTRASENA", nullable=false, length=50)
    public String getHcoConstrasena() {
        return this.hcoConstrasena;
    }
    
    public void setHcoConstrasena(String hcoConstrasena) {
        this.hcoConstrasena = hcoConstrasena;
    }

    
    @Column(name="HCO_FECHA_CAMBIO", nullable=false, length=7)
    public Date getHcoFechaCambio() {
        return this.hcoFechaCambio;
    }
    
    public void setHcoFechaCambio(Date hcoFechaCambio) {
        this.hcoFechaCambio = hcoFechaCambio;
    }

    
    @Column(name="HCO_DETALLE_CAMBIO", length=100)
    public String getHcoDetalleCambio() {
        return this.hcoDetalleCambio;
    }
    
    public void setHcoDetalleCambio(String hcoDetalleCambio) {
        this.hcoDetalleCambio = hcoDetalleCambio;
    }




}


