package com.vortexbird.seguridad.modelo;
// Generated 14/11/2012 05:54:52 PM by Zathura powered by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * SegOpcion generated by Zathura powered by Hibernate-tools(hbm2java)
 */
@Entity
@Table(name="SEG_OPCION"
,schema="PUBLIC"
		)
public class SegOpcion  implements java.io.Serializable {


	private Long opcCodigo;
	private SegUsuario segUsuario;
	private SegGrupoOpcion segGrupoOpcion;
	private String opcNombre;
	private String opcDescripcion;
	private String opcLlaveAcceso;
	private String opcEstadoRegistro;
	private Set<SegPermiso> segPermisos = new HashSet<SegPermiso>(0);

	public SegOpcion() {
	}


	public SegOpcion(Long opcCodigo, SegGrupoOpcion segGrupoOpcion, String opcNombre, String opcEstadoRegistro) {
		this.opcCodigo = opcCodigo;
		this.segGrupoOpcion = segGrupoOpcion;
		this.opcNombre = opcNombre;
		this.opcEstadoRegistro = opcEstadoRegistro;
	}
	public SegOpcion(Long opcCodigo, SegUsuario segUsuario, SegGrupoOpcion segGrupoOpcion, String opcNombre, String opcDescripcion, String opcLlaveAcceso, String opcEstadoRegistro, Set<SegPermiso> segPermisos) {
		this.opcCodigo = opcCodigo;
		this.segUsuario = segUsuario;
		this.segGrupoOpcion = segGrupoOpcion;
		this.opcNombre = opcNombre;
		this.opcDescripcion = opcDescripcion;
		this.opcLlaveAcceso = opcLlaveAcceso;
		this.opcEstadoRegistro = opcEstadoRegistro;
		this.segPermisos = segPermisos;
	}

	@Id 
	@SequenceGenerator(name = "seg_opcion_opc_codigo_seq", sequenceName = "seg_opcion_opc_codigo_seq")
	@GeneratedValue(generator = "seg_opcion_opc_codigo_seq", strategy = GenerationType.SEQUENCE)
	@Column(name="OPC_CODIGO", unique=true, nullable=false)
	public Long getOpcCodigo() {
		return this.opcCodigo;
	}

	public void setOpcCodigo(Long opcCodigo) {
		this.opcCodigo = opcCodigo;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="MOD_USU_CODIGO")
	public SegUsuario getSegUsuario() {
		return this.segUsuario;
	}

	public void setSegUsuario(SegUsuario segUsuario) {
		this.segUsuario = segUsuario;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="SEG_GRUPO_OPCION_GRU_CODIGO", nullable=false)
	public SegGrupoOpcion getSegGrupoOpcion() {
		return this.segGrupoOpcion;
	}

	public void setSegGrupoOpcion(SegGrupoOpcion segGrupoOpcion) {
		this.segGrupoOpcion = segGrupoOpcion;
	}


	@Column(name="OPC_NOMBRE", nullable=false, length=100)
	public String getOpcNombre() {
		return this.opcNombre;
	}

	public void setOpcNombre(String opcNombre) {
		this.opcNombre = opcNombre;
	}


	@Column(name="OPC_DESCRIPCION", length=200)
	public String getOpcDescripcion() {
		return this.opcDescripcion;
	}

	public void setOpcDescripcion(String opcDescripcion) {
		this.opcDescripcion = opcDescripcion;
	}


	@Column(name="OPC_LLAVE_ACCESO", length=200)
	public String getOpcLlaveAcceso() {
		return this.opcLlaveAcceso;
	}

	public void setOpcLlaveAcceso(String opcLlaveAcceso) {
		this.opcLlaveAcceso = opcLlaveAcceso;
	}


	@Column(name="OPC_ESTADO_REGISTRO", nullable=false, length=1)
	public String getOpcEstadoRegistro() {
		return this.opcEstadoRegistro;
	}

	public void setOpcEstadoRegistro(String opcEstadoRegistro) {
		this.opcEstadoRegistro = opcEstadoRegistro;
	}

	@OneToMany(fetch=FetchType.LAZY, mappedBy="segOpcion")
	public Set<SegPermiso> getSegPermisos() {
		return this.segPermisos;
	}

	public void setSegPermisos(Set<SegPermiso> segPermisos) {
		this.segPermisos = segPermisos;
	}




}


