package co.edu.usbcali.mathusb.modelo;
// Generated 23-mar-2016 0:44:34 by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * DetalleEvaluacion generated by hbm2java
 */
public class DetalleEvaluacion  implements java.io.Serializable {


     private Long deevId;
     private Evaluacion evaluacion;
     private Date fechaInicioPublicacion;
     private Date fechaFinPublicacion;
     private Date fechaCreacion;
     private Long corte;
     private String asunto;

    public DetalleEvaluacion() {
    }

	
    public DetalleEvaluacion(Long deevId, Date fechaInicioPublicacion, Date fechaFinPublicacion, Date fechaCreacion, Long corte) {
        this.deevId = deevId;
        this.fechaInicioPublicacion = fechaInicioPublicacion;
        this.fechaFinPublicacion = fechaFinPublicacion;
        this.fechaCreacion = fechaCreacion;
        this.corte = corte;
    }
    public DetalleEvaluacion(Long deevId, Evaluacion evaluacion, Date fechaInicioPublicacion, Date fechaFinPublicacion, Date fechaCreacion, Long corte, String asunto) {
       this.deevId = deevId;
       this.evaluacion = evaluacion;
       this.fechaInicioPublicacion = fechaInicioPublicacion;
       this.fechaFinPublicacion = fechaFinPublicacion;
       this.fechaCreacion = fechaCreacion;
       this.corte = corte;
       this.asunto = asunto;
    }
   
    public Long getDeevId() {
        return this.deevId;
    }
    
    public void setDeevId(Long deevId) {
        this.deevId = deevId;
    }
    public Evaluacion getEvaluacion() {
        return this.evaluacion;
    }
    
    public void setEvaluacion(Evaluacion evaluacion) {
        this.evaluacion = evaluacion;
    }
    public Date getFechaInicioPublicacion() {
        return this.fechaInicioPublicacion;
    }
    
    public void setFechaInicioPublicacion(Date fechaInicioPublicacion) {
        this.fechaInicioPublicacion = fechaInicioPublicacion;
    }
    public Date getFechaFinPublicacion() {
        return this.fechaFinPublicacion;
    }
    
    public void setFechaFinPublicacion(Date fechaFinPublicacion) {
        this.fechaFinPublicacion = fechaFinPublicacion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Long getCorte() {
        return this.corte;
    }
    
    public void setCorte(Long corte) {
        this.corte = corte;
    }
    public String getAsunto() {
        return this.asunto;
    }
    
    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }




}


