package co.edu.usbcali.mathusb.modelo;
// Generated 23-mar-2016 0:44:34 by Hibernate Tools 4.0.0



/**
 * Parametro generated by hbm2java
 */
public class Parametro  implements java.io.Serializable {


     private Long paramId;
     private String descripcionParametros;
     private String valorParametro;
     private String estadoRegistro;

    public Parametro() {
    }

	
    public Parametro(Long paramId, String valorParametro, String estadoRegistro) {
        this.paramId = paramId;
        this.valorParametro = valorParametro;
        this.estadoRegistro = estadoRegistro;
    }
    public Parametro(Long paramId, String descripcionParametros, String valorParametro, String estadoRegistro) {
       this.paramId = paramId;
       this.descripcionParametros = descripcionParametros;
       this.valorParametro = valorParametro;
       this.estadoRegistro = estadoRegistro;
    }
   
    public Long getParamId() {
        return this.paramId;
    }
    
    public void setParamId(Long paramId) {
        this.paramId = paramId;
    }
    public String getDescripcionParametros() {
        return this.descripcionParametros;
    }
    
    public void setDescripcionParametros(String descripcionParametros) {
        this.descripcionParametros = descripcionParametros;
    }
    public String getValorParametro() {
        return this.valorParametro;
    }
    
    public void setValorParametro(String valorParametro) {
        this.valorParametro = valorParametro;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }




}


