package co.edu.usbcali.mathusb.modelo;
// Generated 23-mar-2016 0:44:34 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * Respuesta generated by hbm2java
 */
public class Respuesta  implements java.io.Serializable {


     private Long respId;
     private String descripcionRespuesta;
     private Set<EvaPregRes> evaPregReses = new HashSet<EvaPregRes>(0);

    public Respuesta() {
    }

	
    public Respuesta(Long respId, String descripcionRespuesta) {
        this.respId = respId;
        this.descripcionRespuesta = descripcionRespuesta;
    }
    public Respuesta(Long respId, String descripcionRespuesta, Set<EvaPregRes> evaPregReses) {
       this.respId = respId;
       this.descripcionRespuesta = descripcionRespuesta;
       this.evaPregReses = evaPregReses;
    }
   
    public Long getRespId() {
        return this.respId;
    }
    
    public void setRespId(Long respId) {
        this.respId = respId;
    }
    public String getDescripcionRespuesta() {
        return this.descripcionRespuesta;
    }
    
    public void setDescripcionRespuesta(String descripcionRespuesta) {
        this.descripcionRespuesta = descripcionRespuesta;
    }
    public Set<EvaPregRes> getEvaPregReses() {
        return this.evaPregReses;
    }
    
    public void setEvaPregReses(Set<EvaPregRes> evaPregReses) {
        this.evaPregReses = evaPregReses;
    }




}


