package co.edu.usbcali.mathusb.modelo;
// Generated 23-mar-2016 0:44:34 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * TipoEvaluacion generated by hbm2java
 */
public class TipoEvaluacion  implements java.io.Serializable {


     private Long tievId;
     private String descripcionTipoEvaluacion;
     private String nombreCorto;
     private Set<Evaluacion> evaluacions = new HashSet<Evaluacion>(0);

    public TipoEvaluacion() {
    }

	
    public TipoEvaluacion(Long tievId, String descripcionTipoEvaluacion, String nombreCorto) {
        this.tievId = tievId;
        this.descripcionTipoEvaluacion = descripcionTipoEvaluacion;
        this.nombreCorto = nombreCorto;
    }
    public TipoEvaluacion(Long tievId, String descripcionTipoEvaluacion, String nombreCorto, Set<Evaluacion> evaluacions) {
       this.tievId = tievId;
       this.descripcionTipoEvaluacion = descripcionTipoEvaluacion;
       this.nombreCorto = nombreCorto;
       this.evaluacions = evaluacions;
    }
   
    public Long getTievId() {
        return this.tievId;
    }
    
    public void setTievId(Long tievId) {
        this.tievId = tievId;
    }
    public String getDescripcionTipoEvaluacion() {
        return this.descripcionTipoEvaluacion;
    }
    
    public void setDescripcionTipoEvaluacion(String descripcionTipoEvaluacion) {
        this.descripcionTipoEvaluacion = descripcionTipoEvaluacion;
    }
    public String getNombreCorto() {
        return this.nombreCorto;
    }
    
    public void setNombreCorto(String nombreCorto) {
        this.nombreCorto = nombreCorto;
    }
    public Set<Evaluacion> getEvaluacions() {
        return this.evaluacions;
    }
    
    public void setEvaluacions(Set<Evaluacion> evaluacions) {
        this.evaluacions = evaluacions;
    }




}


