package co.edu.usbcali.mathusb.modelo;
// Generated 15/05/2016 07:07:18 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * Evaluacion generated by hbm2java
 */
public class Evaluacion  implements java.io.Serializable {


     private Long evalId;
     private Grupo grupo;
     private TipoEvaluacion tipoEvaluacion;
     private String estadoRegistro;
     private Set<UsuarioEvaluacion> usuarioEvaluacions = new HashSet<UsuarioEvaluacion>(0);
     private Set<EvaPregRes> evaPregReses = new HashSet<EvaPregRes>(0);
     private Set<DetalleEvaluacion> detalleEvaluacions = new HashSet<DetalleEvaluacion>(0);

    public Evaluacion() {
    }

	
    public Evaluacion(Long evalId, String estadoRegistro) {
        this.evalId = evalId;
        this.estadoRegistro = estadoRegistro;
    }
    public Evaluacion(Long evalId, Grupo grupo, TipoEvaluacion tipoEvaluacion, String estadoRegistro, Set<UsuarioEvaluacion> usuarioEvaluacions, Set<EvaPregRes> evaPregReses, Set<DetalleEvaluacion> detalleEvaluacions) {
       this.evalId = evalId;
       this.grupo = grupo;
       this.tipoEvaluacion = tipoEvaluacion;
       this.estadoRegistro = estadoRegistro;
       this.usuarioEvaluacions = usuarioEvaluacions;
       this.evaPregReses = evaPregReses;
       this.detalleEvaluacions = detalleEvaluacions;
    }
   
    public Long getEvalId() {
        return this.evalId;
    }
    
    public void setEvalId(Long evalId) {
        this.evalId = evalId;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public TipoEvaluacion getTipoEvaluacion() {
        return this.tipoEvaluacion;
    }
    
    public void setTipoEvaluacion(TipoEvaluacion tipoEvaluacion) {
        this.tipoEvaluacion = tipoEvaluacion;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set<UsuarioEvaluacion> getUsuarioEvaluacions() {
        return this.usuarioEvaluacions;
    }
    
    public void setUsuarioEvaluacions(Set<UsuarioEvaluacion> usuarioEvaluacions) {
        this.usuarioEvaluacions = usuarioEvaluacions;
    }
    public Set<EvaPregRes> getEvaPregReses() {
        return this.evaPregReses;
    }
    
    public void setEvaPregReses(Set<EvaPregRes> evaPregReses) {
        this.evaPregReses = evaPregReses;
    }
    public Set<DetalleEvaluacion> getDetalleEvaluacions() {
        return this.detalleEvaluacions;
    }
    
    public void setDetalleEvaluacions(Set<DetalleEvaluacion> detalleEvaluacions) {
        this.detalleEvaluacions = detalleEvaluacions;
    }




}


