package co.edu.usbcali.mathusb.modelo;
// Generated 23-mar-2016 0:44:34 by Hibernate Tools 4.0.0



/**
 * EvaPregRes generated by hbm2java
 */
public class EvaPregRes  implements java.io.Serializable {


     private Long evprId;
     private Respuesta respuesta;
     private Pregunta pregunta;
     private Evaluacion evaluacion;
     private Long indicePregunta;
     private Usuario usuario;

    public EvaPregRes() {
    }

	
    public EvaPregRes(Long evprId, Long indicePregunta) {
        this.evprId = evprId;
        this.indicePregunta = indicePregunta;
    }
    public EvaPregRes(Long evprId, Respuesta respuesta, Pregunta pregunta, Evaluacion evaluacion, Long indicePregunta) {
       this.evprId = evprId;
       this.respuesta = respuesta;
       this.pregunta = pregunta;
       this.evaluacion = evaluacion;
       this.indicePregunta = indicePregunta;
    }
   
    public Long getEvprId() {
        return this.evprId;
    }
    
    public void setEvprId(Long evprId) {
        this.evprId = evprId;
    }
    public Respuesta getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(Respuesta respuesta) {
        this.respuesta = respuesta;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public Evaluacion getEvaluacion() {
        return this.evaluacion;
    }
    
    public void setEvaluacion(Evaluacion evaluacion) {
        this.evaluacion = evaluacion;
    }
    public Long getIndicePregunta() {
        return this.indicePregunta;
    }
    
    public void setIndicePregunta(Long indicePregunta) {
        this.indicePregunta = indicePregunta;
    }


	public Usuario getUsuario() {
		return usuario;
	}


	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}



}


