package co.edu.usbcali.mathusb.modelo;
// Generated 23-mar-2016 0:44:34 by Hibernate Tools 4.0.0



/**
 * GrupoUsuario generated by hbm2java
 */
public class GrupoUsuario  implements java.io.Serializable {


     private Long grusId;
     private Usuario usuario;
     private Grupo grupo;

    public GrupoUsuario() {
    }

	
    public GrupoUsuario(Long grusId) {
        this.grusId = grusId;
    }
    public GrupoUsuario(Long grusId, Usuario usuario, Grupo grupo) {
       this.grusId = grusId;
       this.usuario = usuario;
       this.grupo = grupo;
    }
   
    public Long getGrusId() {
        return this.grusId;
    }
    
    public void setGrusId(Long grusId) {
        this.grusId = grusId;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }




}


