package co.edu.usbcali.mathusb.modelo;
// Generated 15/05/2016 07:07:18 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta  implements java.io.Serializable {


	 private Long pregId;
	 private Tema tema;
	 private String descripcionPregunta;
	 private String descripcionRespuestaCorrecta;
	 private String descripcionRespuesta1;
	 private String descripcionRespuesta2;
	 private String descripcionRespuesta3;
     private String tipoRespuesta;
     private Set<EvaPregRes> evaPregReses = new HashSet<EvaPregRes>(0);
     
   public Pregunta(){} 
   
    public Pregunta(Tema tema, String descripcionPregunta, String descripcionRespuestaCorrecta,
			String descripcionRespuesta1, String descripcionRespuesta2, String descripcionRespuesta3,
			String tipoRespuesta) {
		this.tema = tema;
		this.descripcionPregunta = descripcionPregunta;
		this.descripcionRespuestaCorrecta = descripcionRespuestaCorrecta;
		this.descripcionRespuesta1 = descripcionRespuesta1;
		this.descripcionRespuesta2 = descripcionRespuesta2;
		this.descripcionRespuesta3 = descripcionRespuesta3;
		this.tipoRespuesta = tipoRespuesta;
	}

    
    
	public Set<EvaPregRes> getEvaPregReses() {
		return evaPregReses;
	}

	public void setEvaPregReses(Set<EvaPregRes> evaPregReses) {
		this.evaPregReses = evaPregReses;
	}

	public String getTipoRespuesta() {
		return tipoRespuesta;
	}

	public void setTipoRespuesta(String tipoRespuesta) {
		this.tipoRespuesta = tipoRespuesta;
	}

	public Long getPregId() {
        return this.pregId;
    }
    
    public void setPregId(Long pregId) {
        this.pregId = pregId;
    }
    public Tema getTema() {
        return this.tema;
    }
    
    public void setTema(Tema tema) {
        this.tema = tema;
    }
    public String getDescripcionPregunta() {
        return this.descripcionPregunta;
    }
    
    public void setDescripcionPregunta(String descripcionPregunta) {
        this.descripcionPregunta = descripcionPregunta;
    }


	public String getDescripcionRespuestaCorrecta() {
		return descripcionRespuestaCorrecta;
	}


	public void setDescripcionRespuestaCorrecta(String descripcionRespuestaCorrecta) {
		this.descripcionRespuestaCorrecta = descripcionRespuestaCorrecta;
	}


	public String getDescripcionRespuesta1() {
		return descripcionRespuesta1;
	}


	public void setDescripcionRespuesta1(String descripcionRespuesta1) {
		this.descripcionRespuesta1 = descripcionRespuesta1;
	}


	public String getDescripcionRespuesta2() {
		return descripcionRespuesta2;
	}


	public void setDescripcionRespuesta2(String descripcionRespuesta2) {
		this.descripcionRespuesta2 = descripcionRespuesta2;
	}


	public String getDescripcionRespuesta3() {
		return descripcionRespuesta3;
	}


	public void setDescripcionRespuesta3(String descripcionRespuesta3) {
		this.descripcionRespuesta3 = descripcionRespuesta3;
	}
    
}


