package co.edu.usbcali.mathusb.modelo;
// Generated 15/05/2016 07:07:18 PM by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta  implements java.io.Serializable {


     private Long pregId;
     private Tema tema;
     private String descripcionPregunta;
     private Set<EvaPregRes> evaPregReses = new HashSet<EvaPregRes>(0);

    public Pregunta() {
    }

	
    public Pregunta(Long pregId, String descripcionPregunta) {
        this.pregId = pregId;
        this.descripcionPregunta = descripcionPregunta;
    }
    public Pregunta(Long pregId, Tema tema, String descripcionPregunta, Set<EvaPregRes> evaPregReses) {
       this.pregId = pregId;
       this.tema = tema;
       this.descripcionPregunta = descripcionPregunta;
       this.evaPregReses = evaPregReses;
    }
   
    public Long getPregId() {
        return this.pregId;
    }
    
    public void setPregId(Long pregId) {
        this.pregId = pregId;
    }
    public Tema getTema() {
        return this.tema;
    }
    
    public void setTema(Tema tema) {
        this.tema = tema;
    }
    public String getDescripcionPregunta() {
        return this.descripcionPregunta;
    }
    
    public void setDescripcionPregunta(String descripcionPregunta) {
        this.descripcionPregunta = descripcionPregunta;
    }
    public Set<EvaPregRes> getEvaPregReses() {
        return this.evaPregReses;
    }
    
    public void setEvaPregReses(Set<EvaPregRes> evaPregReses) {
        this.evaPregReses = evaPregReses;
    }




}


