package co.edu.usbcali.mathusb.modelo;
// Generated 23-mar-2016 0:44:34 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * Tema generated by hbm2java
 */
public class Tema  implements java.io.Serializable {


     private Long temaId;
     private String descripcionTema;
     private String tituloTema;
     private String palabrasClave;
     private Set<Evaluacion> evaluacions = new HashSet<Evaluacion>(0);

    public Tema() {
    }

	
    public Tema(Long temaId, String descripcionTema, String palabrasClave) {
        this.temaId = temaId;
        this.descripcionTema = descripcionTema;
        this.palabrasClave = palabrasClave;
    }
    public Tema(Long temaId, String descripcionTema, String tituloTema, String palabrasClave, Set<Evaluacion> evaluacions) {
       this.temaId = temaId;
       this.descripcionTema = descripcionTema;
       this.tituloTema = tituloTema;
       this.palabrasClave = palabrasClave;
       this.evaluacions = evaluacions;
    }
   
    public Long getTemaId() {
        return this.temaId;
    }
    
    public void setTemaId(Long temaId) {
        this.temaId = temaId;
    }
    public String getDescripcionTema() {
        return this.descripcionTema;
    }
    
    public void setDescripcionTema(String descripcionTema) {
        this.descripcionTema = descripcionTema;
    }
    public String getTituloTema() {
        return this.tituloTema;
    }
    
    public void setTituloTema(String tituloTema) {
        this.tituloTema = tituloTema;
    }
    public String getPalabrasClave() {
        return this.palabrasClave;
    }
    
    public void setPalabrasClave(String palabrasClave) {
        this.palabrasClave = palabrasClave;
    }
    public Set<Evaluacion> getEvaluacions() {
        return this.evaluacions;
    }
    
    public void setEvaluacions(Set<Evaluacion> evaluacions) {
        this.evaluacions = evaluacions;
    }




}


