package co.edu.usbcali.mathusb.modelo;
// Generated 23-mar-2016 0:44:34 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * TipoUsuario generated by hbm2java
 */
public class TipoUsuario  implements java.io.Serializable {


     private Long tiusId;
     private String descripcionTipoDeUsuario;
     private String nombreCorto;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public TipoUsuario() {
    }

	
    public TipoUsuario(Long tiusId, String descripcionTipoDeUsuario, String nombreCorto) {
        this.tiusId = tiusId;
        this.descripcionTipoDeUsuario = descripcionTipoDeUsuario;
        this.nombreCorto = nombreCorto;
    }
    public TipoUsuario(Long tiusId, String descripcionTipoDeUsuario, String nombreCorto, Set<Usuario> usuarios) {
       this.tiusId = tiusId;
       this.descripcionTipoDeUsuario = descripcionTipoDeUsuario;
       this.nombreCorto = nombreCorto;
       this.usuarios = usuarios;
    }
   
    public Long getTiusId() {
        return this.tiusId;
    }
    
    public void setTiusId(Long tiusId) {
        this.tiusId = tiusId;
    }
    public String getDescripcionTipoDeUsuario() {
        return this.descripcionTipoDeUsuario;
    }
    
    public void setDescripcionTipoDeUsuario(String descripcionTipoDeUsuario) {
        this.descripcionTipoDeUsuario = descripcionTipoDeUsuario;
    }
    public String getNombreCorto() {
        return this.nombreCorto;
    }
    
    public void setNombreCorto(String nombreCorto) {
        this.nombreCorto = nombreCorto;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


