package co.edu.usbcali.mathusb.modelo;
// Generated 23-mar-2016 0:44:34 by Hibernate Tools 4.0.0



/**
 * UsuarioEvaluacion generated by hbm2java
 */
public class UsuarioEvaluacion  implements java.io.Serializable {


     private Long usevId;
     private Usuario usuario;
     private Evaluacion evaluacion;

    public UsuarioEvaluacion() {
    }

	
    public UsuarioEvaluacion(Long usevId) {
        this.usevId = usevId;
    }
    public UsuarioEvaluacion(Long usevId, Usuario usuario, Evaluacion evaluacion) {
       this.usevId = usevId;
       this.usuario = usuario;
       this.evaluacion = evaluacion;
    }
   
    public Long getUsevId() {
        return this.usevId;
    }
    
    public void setUsevId(Long usevId) {
        this.usevId = usevId;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Evaluacion getEvaluacion() {
        return this.evaluacion;
    }
    
    public void setEvaluacion(Evaluacion evaluacion) {
        this.evaluacion = evaluacion;
    }




}


