package co.edu.usbcali.mathusb.modelo;
// Generated 23-mar-2016 0:44:34 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Long usuaId;
     private TipoUsuario tipoUsuario;
     private String nombreUsuario;
     private String apellidoUsuario;
     private String emailUsuario;
     private String passwordUsuario;
     private String codigoUsuario;
     private String estadoRegistro;
     private Set<Comentario> comentarios = new HashSet<Comentario>(0);
     private Set<UsuarioEvaluacion> usuarioEvaluacions = new HashSet<UsuarioEvaluacion>(0);
     private Set<GrupoUsuario> grupoUsuarios = new HashSet<GrupoUsuario>(0);
     private Set<Herramienta> herramientas = new HashSet<Herramienta>(0);

    public Usuario() {
    }

	
    public Usuario(Long usuaId, String nombreUsuario, String apellidoUsuario, String emailUsuario, String passwordUsuario, String codigoUsuario, String estadoRegistro) {
        this.usuaId = usuaId;
        this.nombreUsuario = nombreUsuario;
        this.apellidoUsuario = apellidoUsuario;
        this.emailUsuario = emailUsuario;
        this.passwordUsuario = passwordUsuario;
        this.codigoUsuario = codigoUsuario;
        this.estadoRegistro = estadoRegistro;
    }
    public Usuario(Long usuaId, TipoUsuario tipoUsuario, String nombreUsuario, String apellidoUsuario, String emailUsuario, String passwordUsuario, String codigoUsuario, String estadoRegistro, Set<Comentario> comentarios, Set<UsuarioEvaluacion> usuarioEvaluacions, Set<GrupoUsuario> grupoUsuarios, Set<Herramienta> herramientas) {
       this.usuaId = usuaId;
       this.tipoUsuario = tipoUsuario;
       this.nombreUsuario = nombreUsuario;
       this.apellidoUsuario = apellidoUsuario;
       this.emailUsuario = emailUsuario;
       this.passwordUsuario = passwordUsuario;
       this.codigoUsuario = codigoUsuario;
       this.estadoRegistro = estadoRegistro;
       this.comentarios = comentarios;
       this.usuarioEvaluacions = usuarioEvaluacions;
       this.grupoUsuarios = grupoUsuarios;
       this.herramientas = herramientas;
    }
   
    public Long getUsuaId() {
        return this.usuaId;
    }
    
    public void setUsuaId(Long usuaId) {
        this.usuaId = usuaId;
    }
    public TipoUsuario getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getApellidoUsuario() {
        return this.apellidoUsuario;
    }
    
    public void setApellidoUsuario(String apellidoUsuario) {
        this.apellidoUsuario = apellidoUsuario;
    }
    public String getEmailUsuario() {
        return this.emailUsuario;
    }
    
    public void setEmailUsuario(String emailUsuario) {
        this.emailUsuario = emailUsuario;
    }
    public String getPasswordUsuario() {
        return this.passwordUsuario;
    }
    
    public void setPasswordUsuario(String passwordUsuario) {
        this.passwordUsuario = passwordUsuario;
    }
    public String getCodigoUsuario() {
        return this.codigoUsuario;
    }
    
    public void setCodigoUsuario(String codigoUsuario) {
        this.codigoUsuario = codigoUsuario;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Set<Comentario> getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set<Comentario> comentarios) {
        this.comentarios = comentarios;
    }
    public Set<UsuarioEvaluacion> getUsuarioEvaluacions() {
        return this.usuarioEvaluacions;
    }
    
    public void setUsuarioEvaluacions(Set<UsuarioEvaluacion> usuarioEvaluacions) {
        this.usuarioEvaluacions = usuarioEvaluacions;
    }
    public Set<GrupoUsuario> getGrupoUsuarios() {
        return this.grupoUsuarios;
    }
    
    public void setGrupoUsuarios(Set<GrupoUsuario> grupoUsuarios) {
        this.grupoUsuarios = grupoUsuarios;
    }
    public Set<Herramienta> getHerramientas() {
        return this.herramientas;
    }
    
    public void setHerramientas(Set<Herramienta> herramientas) {
        this.herramientas = herramientas;
    }




}


