package com.vortexbird.seguridad.modelo;
// Generated 14/11/2012 05:54:52 PM by Zathura powered by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * SegRolUsuario generated by Zathura powered by Hibernate-tools(hbm2java)
 */
@Entity
@Table(name="SEG_ROL_USUARIO"
,schema="PUBLIC"
		)
public class SegRolUsuario  implements java.io.Serializable {


	private Long rluCodigo;
	private SegUsuario segUsuarioBySegUsuarioUsuCodigo;
	private SegUsuario segUsuarioByModUsuCodigo;
	private SegRol segRol;
	private String rluEstadoRegistro;

	public SegRolUsuario() {
	}


	public SegRolUsuario(Long rluCodigo, SegUsuario segUsuarioBySegUsuarioUsuCodigo, SegRol segRol, String rluEstadoRegistro) {
		this.rluCodigo = rluCodigo;
		this.segUsuarioBySegUsuarioUsuCodigo = segUsuarioBySegUsuarioUsuCodigo;
		this.segRol = segRol;
		this.rluEstadoRegistro = rluEstadoRegistro;
	}
	public SegRolUsuario(Long rluCodigo, SegUsuario segUsuarioBySegUsuarioUsuCodigo, SegUsuario segUsuarioByModUsuCodigo, SegRol segRol, String rluEstadoRegistro) {
		this.rluCodigo = rluCodigo;
		this.segUsuarioBySegUsuarioUsuCodigo = segUsuarioBySegUsuarioUsuCodigo;
		this.segUsuarioByModUsuCodigo = segUsuarioByModUsuCodigo;
		this.segRol = segRol;
		this.rluEstadoRegistro = rluEstadoRegistro;
	}

	@Id 
	@SequenceGenerator(name = "seg_rol_usuario_rlu_codigo_seq", sequenceName = "seg_rol_usuario_rlu_codigo_seq", initialValue = 1, allocationSize = 1)
	@GeneratedValue(generator = "seg_rol_usuario_rlu_codigo_seq", strategy = GenerationType.SEQUENCE)
	@Column(name="RLU_CODIGO", unique=true, nullable=false, precision=10, scale=0)
	public Long getRluCodigo() {
		return this.rluCodigo;
	}

	public void setRluCodigo(Long rluCodigo) {
		this.rluCodigo = rluCodigo;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="SEG_USUARIO_USU_CODIGO", nullable=false)
	public SegUsuario getSegUsuarioBySegUsuarioUsuCodigo() {
		return this.segUsuarioBySegUsuarioUsuCodigo;
	}

	public void setSegUsuarioBySegUsuarioUsuCodigo(SegUsuario segUsuarioBySegUsuarioUsuCodigo) {
		this.segUsuarioBySegUsuarioUsuCodigo = segUsuarioBySegUsuarioUsuCodigo;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="MOD_USU_CODIGO")
	public SegUsuario getSegUsuarioByModUsuCodigo() {
		return this.segUsuarioByModUsuCodigo;
	}

	public void setSegUsuarioByModUsuCodigo(SegUsuario segUsuarioByModUsuCodigo) {
		this.segUsuarioByModUsuCodigo = segUsuarioByModUsuCodigo;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="SEG_ROL_ROL_CODIGO", nullable=false)
	public SegRol getSegRol() {
		return this.segRol;
	}

	public void setSegRol(SegRol segRol) {
		this.segRol = segRol;
	}


	@Column(name="RLU_ESTADO_REGISTRO", nullable=false, length=1)
	public String getRluEstadoRegistro() {
		return this.rluEstadoRegistro;
	}

	public void setRluEstadoRegistro(String rluEstadoRegistro) {
		this.rluEstadoRegistro = rluEstadoRegistro;
	}




}


