package co.edu.usbcali.mathusb.modelo;
// Generated 23-mar-2016 0:44:34 by Hibernate Tools 4.0.0


import java.util.Date;

/**
 * Herramienta generated by hbm2java
 */
public class Herramienta  implements java.io.Serializable {


     private Long herrId;
     private Usuario usuario;
     private TipoHerramienta tipoHerramienta;
     private String valorHerramienta;
     private String descripcionHerramienta;
     private String estadoRegistro;
     private Date fechaPublicacion;

    public Herramienta() {
    }

	
    public Herramienta(Long herrId, String valorHerramienta, String descripcionHerramienta, String estadoRegistro, Date fechaPublicacion) {
        this.herrId = herrId;
        this.valorHerramienta = valorHerramienta;
        this.descripcionHerramienta = descripcionHerramienta;
        this.estadoRegistro = estadoRegistro;
        this.fechaPublicacion = fechaPublicacion;
    }
    public Herramienta(Long herrId, Usuario usuario, TipoHerramienta tipoHerramienta, String valorHerramienta, String descripcionHerramienta, String estadoRegistro, Date fechaPublicacion) {
       this.herrId = herrId;
       this.usuario = usuario;
       this.tipoHerramienta = tipoHerramienta;
       this.valorHerramienta = valorHerramienta;
       this.descripcionHerramienta = descripcionHerramienta;
       this.estadoRegistro = estadoRegistro;
       this.fechaPublicacion = fechaPublicacion;
    }
   
    public Long getHerrId() {
        return this.herrId;
    }
    
    public void setHerrId(Long herrId) {
        this.herrId = herrId;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public TipoHerramienta getTipoHerramienta() {
        return this.tipoHerramienta;
    }
    
    public void setTipoHerramienta(TipoHerramienta tipoHerramienta) {
        this.tipoHerramienta = tipoHerramienta;
    }
    public String getValorHerramienta() {
        return this.valorHerramienta;
    }
    
    public void setValorHerramienta(String valorHerramienta) {
        this.valorHerramienta = valorHerramienta;
    }
    public String getDescripcionHerramienta() {
        return this.descripcionHerramienta;
    }
    
    public void setDescripcionHerramienta(String descripcionHerramienta) {
        this.descripcionHerramienta = descripcionHerramienta;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public Date getFechaPublicacion() {
        return this.fechaPublicacion;
    }
    
    public void setFechaPublicacion(Date fechaPublicacion) {
        this.fechaPublicacion = fechaPublicacion;
    }




}


